server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: buildpcchecker
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lookatwidget@gmail.com  # Thay bằng email của bạn
    password: ${MAIL_PASSWORD}      # Thay bằng App Password của Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  base-url: http://localhost:8080/identity  # URL base của ứng dụng
  file:
    upload-dir: ${user.dir}/uploads/images
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    folder: ${CLOUDINARY_FOLDER:buildpcchecker}
  openapi:
    dev-url: http://localhost:8080

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 300 # in seconds
  refreshable-duration: 1200 # seconds

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
  show-actuator: false
